name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Environment
        run: |
            echo "Event - ${{ github.event_name }}"
            echo "Runner ${{ runner.os }}"
            echo "The name of your branch - ${{ github.repository }}/${{ github.ref }}"
      - name: checkout
        uses: actions/checkout@v2
      - name: Install JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Run deployment test using maven
        run: .github/workflows/run-deployment-test.sh
      - name: After run status
        run: echo "🍏 This job's status is ${{ job.status }}."